# Generated by Django 4.2.1 on 2023-05-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myList', models.CharField(blank=True, default=None, max_length=40)),
            ],
        ),
    ]
