# Generated by Django 4.2.1 on 2023-06-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='myModel2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
