# Generated by Django 4.2.1 on 2023-06-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_alter_mymodel_mymodel3_alter_mymodel_mymodel4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='myModel1',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
